<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>AgendaLivreWindows</AssemblyName>
    <RootNamespace>AgendaLivre.Windows</RootNamespace>
    <Product>Agenda Livre</Product>
    <AssemblyTitle>Agenda Livre</AssemblyTitle>
    <Company>Nagazaki Software</Company>
    <Version>1.0.2026.1</Version>
    <AssemblyVersion>1.0.2026.1</AssemblyVersion>
    <FileVersion>1.0.2026.1</FileVersion>
    <InformationalVersion>1.0.2026.1</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MaterialDesignThemes" Version="5.3.2" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\agenda-livre-logo-source.png" />
    <Resource Include="Assets\agenda-livre-logo-dark-transparent.png" />
    <Resource Include="Assets\Themes\*.png" />
  </ItemGroup>

</Project>
