<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>BalcaoLivreAdmin</AssemblyName>
    <Product>Balcao Livre PDV Admin</Product>
    <AssemblyTitle>Balcao Livre PDV Admin</AssemblyTitle>
    <Company>Balcao Livre</Company>
    <Version>1.1.0</Version>
    <AssemblyVersion>1.1.0.0</AssemblyVersion>
    <FileVersion>1.1.0.0</FileVersion>
    <InformationalVersion>1.1.0</InformationalVersion>
  </PropertyGroup>
</Project>
