<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>BalcaoLivreAdmin</AssemblyName>
    <Product>Balcao Livre PDV Admin</Product>
    <AssemblyTitle>Balcao Livre PDV Admin</AssemblyTitle>
    <Company>Nagazaki Software</Company>
    <Version>1.2.2026</Version>
    <AssemblyVersion>1.2.2026.0</AssemblyVersion>
    <FileVersion>1.2.2026.0</FileVersion>
    <InformationalVersion>1.2.2026</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>
</Project>
